### ISSUE TITLE
Componentize Parts of the UI

### ISSUE THREAD

**Issue by mcb2003** [bitphoenixsoftware/cassian#4]
There are many pieces of the UI where code is repeated, particularly with modals. This becomes an even bigger problem when, as I have been, you try to make the UI more accessible and end up with lots of divs with lots of aria attributes.

**Solution**

The markdown editor, used where rich text is required, has already been broken out in the form of the *simplemde.ejs* include file. I suggest that other parts of the code, perhaps more generalized, should be broken out as well. For example, there should be a *partials/modal-header.ejs* and a *partials/modal-footer.ejs.* Separating the start from the end allows us to much more easily sandwich HTML code in the middle without having to do something hacky like pass it as a variable.

Any options required for each component can be passed during the include, just like in the case of simplemde:

```js
    include("simplemde.ejs", { name: "about", text: user.about })
```

These includes should also be placed in the *views/parts*folder, or perhapse a folder of their own, to stop them from cluttering the main *views* folder.

So, hypothetically, the modal-header.ejs file would look something like this:

```html
    <div class="modal" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="<%= id %>title"
        aria-hidden="true" aria-modal="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="<%= id %>title" aria-level="1">
                        upload background image
                    </h5>
                    <button type="button" data-dismiss="modal" class="close" aria-label="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
```

**Comment by alkalinethunder** [comment]
Hey - sorry I haven't acknowledged this issue yet - only just saw it now.  I haven't worked on this repo for a few weeks as I've been focusing on The Peacenet.  But I guess I already acknowledged the issue in a way as we are currently completely rewriting Cassian to make the user interface more sleek and less spaghettified.  Also working on a REST API so we can have visual studio code integration.

Check the new repos out :)

https://github.com/bitphoenixsoftware/cassian-vue-webapp
https://github.com/bitphoenixsoftware/cassian-api

I'm going to close this issue simply because I'm archiving this version of Cassian in favor of the rewrite.
